from dataclasses import dataclass

# The below code is defining the dataclasses for the artifacts that will be generated by each step of the pipeline.
@dataclass
class DataIngestionArtifacts:
    download_dir_path: str
    extract_dir_path: str
